apiVersion: apps/v1
kind: Deployment
metadata:
  name: netapp-deployment
  labels:
    app: netapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netapp
  template:
    metadata:
      labels:
        app: netapp
    spec:
      containers:
      - name: netflixserver
        image: vimal2019/netflix2025:latest
        ports:
        - containerPort: 8081
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: netapp-service
spec:
  selector:
    app: netapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31110
