apiVersion: apps/v1
kind: Deployment
metadata:
  name: netapp-deployment
  labels:
    app: netflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - name: netflixserver2
        image: vimal2019/nx3:latest
        ports:
        - containerPort: 8081
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: netflix-svc
spec:
  selector:
    app: netflix
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31110
